### ISSUE TITLE
Request Header with a "-" failing

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/plugin-lighthouse#49]
I am running the following command: _**docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:11.9.3-plus1 --config /sitespeed.io/config.json http://www.domain.com/**_ with the contents of config.json being:
```
{
  "lighthouse": {
      "settings": {
        "extra-headers": {"X-Akamai-Bot-Allow":"123"},
        "extraHeaders": {"X-Akamai-Bot-Allow":"123"}
      }
    }
}
```

I get the following error:
```
[2020-03-06 22:44:31] ERROR: Lighthouse could not test http://www.domain.com/ please create an upstream issue: https://github.com/GoogleChrome/lighthouse/issues/new?template=Bug_report.md Error: Protocol error (Network.setExtraHTTPHeaders): Invalid header value, string expected
    at Function.fromProtocolMessage (/lighthouse/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:132:19)
    at /lighthouse/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:123:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-03-06 22:44:31] ERROR: TypeError: Cannot read property 'lhr' of undefined
    at Object.processMessage (/lighthouse/index.js:200:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

If I strip the hyphens from X-Akamai-Bot-Allow, it works, but I need the hyphens as we use this header to allow our sites to not block our sitespeedio tests. Any ideas?

**Comment by soulgalore** [comment]
Does this works now, this looks like bug with Lighthouse?
